CREATE OR REPLACE FUNCTION trigger_A()
  RETURNS TRIGGER
  AS $$
BEGIN
  IF(TG_OP = 'INSERT') THEN
    RETURN NEW;
  ELSIF(TG_OP = 'UPDATE') THEN
    RETURN NEW;
  ELSIF(TG_OP = 'DELETE') THEN
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER trigger_A
  INSTEAD OF INSERT OR UPDATE OR DELETE ON A
  FOR EACH ROW
  EXECUTE FUNCTION trigger_A();

